name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nodejs: [18, 20]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.nodejs }}

    - name: Install
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Check formatting
      run: npm run format:check

    - name: Test
      run: npm test
